### ISSUE TITLE
コメント毎の学校名表示の変更

### ISSUE THREAD

**Issue by ichikawa3** [TaikiFnit/Classwork-BBS#8]
基本的にスレッドは同じ学校内で利用しますので、コメントごとに学校名の表示は必要ないと思われます。たとえば、右上に学校名を表示するなどにしてください。

**Comment by TaikiFnit** [comment]
@ichikawa3 

とりあえず, こんな感じに変えてみました
![screenshot-2017-12-8 - 1](https://user-images.githubusercontent.com/8556774/33747587-2354d798-dc07-11e7-8700-5b451f1f9d68.png)

この画面の使いやすさが一番きもになってくるとおもうので, 後ほどデザインについてはちゃんと考えておきます.

**Comment by ichikawa3** [comment]
修正ありがとう。さしあたりこれで問題ありません。よろしくお願いします。
